name: Python

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  tests:
    name: pytests (${{ matrix.os }} - ${{ matrix.python-version }}, Mambaforge)
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
        python-version: [ '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          environment-file: environment.yml
          python-version: ${{ matrix.python-version }}
          miniforge-version: latest
          miniforge-variant: Mambaforge
          activate-environment: test
          auto-activate-base: false
          use-mamba: true
      - name: Run tests
        run: |
          pytest -vs --log-cli-level=debug

      - name: Build wheels
        run: |
          conda activate test
          mamba install -c conda-forge poetry
          poetry build

      - name: Upload wheels
        if: matrix.python-version == '3.10' && matrix.os == 'ubuntu'
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: dist

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ tests ]
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: wheels
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          miniforge-version: latest
          miniforge-variant: Mambaforge
      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade twine
          twine upload --skip-existing *

