name: Python

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

jobs:
  tests:
    name: pytests (${{ matrix.os }} - ${{ matrix.python-version }}, Miniforge)
    runs-on: ${{ matrix.os }}-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        os: ["ubuntu", "macos", "windows"]
        python-version: [ '3.9', '3.10', '3.11' ]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-file: environment.yml
          channels: conda-forge
          cache-environment: true
          post-cleanup: 'all'
          init-shell: >-
            bash
            powershell
          extra-specs: python=${{ matrix.python-version }}


      - name: Cache cartopy maps
        id: cache-cartopy
        uses: actions/cache@v4
        with:
          path: ~/.local/share/cartopy
          key: cartopy-maps

      - name: Run tests
        run: |
          pytest -vs --log-cli-level=debug

      - name: Build wheels
        run: |
          micromamba install poetry
          poetry build

      - name: Upload wheels
        if: matrix.python-version == '3.10' && matrix.os == 'ubuntu'
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.runs-on }}
          path: dist
          overwrite: true

  release:
    name: Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [ tests ]
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: wheels
          pattern: wheels-*
          merge-multiple: true
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.10'
          miniforge-version: latest
          miniforge-variant: Miniforge
      - name: Publish to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install --upgrade typing-extensions twine
          twine upload --skip-existing *

  merge:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: all-my-files
          pattern: wheels-*
